imports:
  - {resource: console.php}
services:
  TJM\BaseProj\BaseProj:
    $shell: ~
    $opts: '%baseProjOpts%'
  TJM\ShellRunner\ShellRunner: ~
  TJM\BaseProj\Command\:
    autowire: true
    resource: '%paths.project%/src/Command'
    tags: ['console.command']
tjm_console:
  defaultCommand: 'list'
  name: 'base.proj'
  version: '0.1'
